name: build
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'DOCS/**'
      - 'TOOLS/lua/**'
      - '.editorconfig'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE'
      - '.gitignore'
      - 'Copyright'
      - 'README.md'
      - 'RELEASE_NOTES'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mingw:
    runs-on: ubuntu-24.04
    env:
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 500M
      DOWNLOAD_CACHE: ${{ github.workspace }}/.ccache/downloads
      TARGET: ${{ matrix.arch }}-w64-mingw32
      RUST_TARGET: ${{ matrix.arch }}-pc-windows-gnu
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: i686
            wine: wine32
          
    steps:
      - uses: actions/checkout@v6

      - name: Get time
        id: get_time
        run: echo "timestamp=`date +%s%N`" >> $GITHUB_OUTPUT

      - name: Restore cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.TARGET }}-${{ steps.get_time.outputs.timestamp }}
          restore-keys: ${{ env.TARGET }}-

      - name: Install dependencies
        run: |
          rustup target add ${{ env.RUST_TARGET }}
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ccache g++-mingw-w64 python3-pip nasm ninja-build pkgconf
          python -m pip install meson

      - name: Install Meson Wraps
        run: |
          mkdir subprojects -p
          meson wrap install mujs
          meson subprojects download

      - name: Build libraries
        run: |
          ./ci/build-mingw64.sh

      - name: Build with meson
        id: build
        run: |
          ./ci/build-mingw64.sh meson pack

      - name: Print meson log
        if: ${{ failure() && steps.build.outcome == 'failure' }}
        run: |
          cat ./mingw_build/meson-logs/meson-log.txt

      - name: Artifact name
        id: artifact
        run: |
          VERSION_FILE=$(find . -path "*/common/version.h" -type f | head -n 1)
          VER=$(grep VERSION "$VERSION_FILE" | cut -d'"' -f2)
          PR=${{ github.event.pull_request.number && format('-pr{0}', github.event.pull_request.number) || '' }}
          echo "name=mpv-$VER$PR-${{ github.run_id }}-$TARGET" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: artifact/*

      - name: Save Cache
        uses: actions/cache/save@v5
        if: always()
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.TARGET }}-${{ steps.get_time.outputs.timestamp }}

